name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cargo Build
        run: cargo build --verbose
      - name: Cargo Fmt
        run: cargo fmt -- --check
      - name: Cargo clippy
        run: cargo clippy -- -Dwarnings
